### PR TITLE
Update extensions.yml

### PR DESCRIPTION
**Pull request by tidusjar**
Added a package link for the .Net Core Sqlite Extension

### CODE REVIEW

**Comment by odinserj** [comment]
@tidusjar, thank you for interest! Any chance to merge it with the original package?

**Comment by tidusjar** [comment]
Possibly, it's a different assembly as I thought the existing one was still valid!

**Comment by odinserj** [comment]
There's no reason to have one package for .NET Framework, and another one just for .NET Core. Single NuGet package can target both platform, like [Hangfire.Core](https://www.nuget.org/packages/Hangfire.Core/) package itself. It's not a good thing to pollute NuGet Gallery with identical packages, and it's also complicates release management. Did you contact the author of the original SQLite extension for Hangfire?

**Comment by tidusjar** [comment]
Very True, I'll speak to him.

**Pull request closed without merging**
