### PR TITLE
Add Hangfire.RecurringJobCleanUpManager

### PR DESCRIPTION
**Pull request by Ramon-Balaguer**

### CODE REVIEW

**Comment by odinserj** [comment]
Thanks @Ramon-Balaguer, I merging the PR. Have you considered to add more details to the README file with basic information and getting started section?

**Comment by Ramon-Balaguer** [comment]
OK!

**Comment by Ramon-Balaguer** [comment]
> Thanks @Ramon-Balaguer, I merging the PR. Have you considered to add more details to the README file with basic information and getting started section?

Complete!

**Comment by odinserj** [comment]
Great, really nice! Readme and pictures increase chances that extension will gain an interest.

**Pull request merged**
