### PR TITLE
Implemented sticky behaviour for sidenav

### PR DESCRIPTION
**Pull request by danillewin**
Now side navigation panel is fixed during scroll down. Exception: small screens, where window height is lesser than sidenav's height

image

### CODE REVIEW

**Comment by odinserj** [comment]
Awesome @danillewin! Have you considered to put the source code to some js file for cache purposes to avoid requesting each time the page is requested? Also looks like "Uploading image.png" wasn't uploaded.

**Comment by danillewin** [comment]
> Awesome @danillewin! Have you considered to put the source code to some js file for cache purposes to avoid requesting each time the page is requested? Also looks like "Uploading image.png" wasn't uploaded.

@odinserj, great addition, updated!

Also, I've re-uploaded PR's image

**Comment by odinserj** [comment]
Thanks, looks great now. Did you try to do the same with the sidebar in the blog? I believe it should be the same for consistency reasons.

**Comment by danillewin** [comment]
Sure, just going to do it!

**Comment by danillewin** [comment]
I realized, that browser support for `position: sticky` is wide enough, so, I decided  to move from JS implementation to pure CSS solution

**Pull request merged**
